# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Madrid Open Cities Summit
email: opencitiessummit@medialab-prado.es
description: > # this means to ignore newlines until "baseurl:"
  Cities open to citizen innovation. Open Data is a source for knowledge and decision making. How should a city structure teams to ensure that the publication of datasets is compliant with technical and legal frameworks?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opencitiessummit.org/" # the base hostname & protocol for your site
twitter_username: citiesopen
github_username:  medialab-prado

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag